-- ALIENKIND / ENARK OS: DATABASE REPAIR SCRIPT
-- RUN THIS IN YOUR SUPABASE SQL EDITOR TO ENABLE GLOBAL CONFIGURATION SAVING

ALTER TABLE app_config ADD COLUMN IF NOT EXISTS brand_name TEXT DEFAULT 'ENARK';
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#DC2626';
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS hero_title TEXT DEFAULT 'THE_HORIZON_COLLECTION';
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS hero_subtitle TEXT DEFAULT 'SYNERGETIC_STREETWEAR_SYSTEMS';
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS footer_text TEXT DEFAULT 'ENARK // QUANTUM_RETAIL_OS_V4';
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS free_shipping_threshold NUMERIC DEFAULT 5000;
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS cod_enabled BOOLEAN DEFAULT true;
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS show_careers_button BOOLEAN DEFAULT true;

CREATE TABLE IF NOT EXISTS job_postings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    department TEXT NOT NULL,
    location TEXT DEFAULT 'REMOTE',
    type TEXT DEFAULT 'FULL_TIME',
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
